"""Initial migration

Revision ID: 213f2ddf3afc
Revises: 
Create Date: 2023-06-13 19:48:05.684131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213f2ddf3afc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('service_id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('addresses',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address_line1', sa.String(length=50), nullable=True),
    sa.Column('address_line2', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=5), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_addresses_user_id_users')),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('therapists',
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('services_offered', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['services_offered'], ['services.title'], name=op.f('fk_therapists_services_offered_services')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_therapists_user_id_users')),
    sa.PrimaryKeyConstraint('therapist_id')
    )
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('therapist_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=True),
    sa.Column('appointment_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], name=op.f('fk_appointments_service_id_services')),
    sa.ForeignKeyConstraint(['therapist_id'], ['therapists.therapist_id'], name=op.f('fk_appointments_therapist_id_therapists')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_appointments_user_id_users')),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    op.drop_table('therapists')
    op.drop_table('addresses')
    op.drop_table('users')
    op.drop_table('services')
    # ### end Alembic commands ###
