"""updated tables

Revision ID: 37c14fca5cfe
Revises: 9116f70715e1
Create Date: 2023-06-26 15:49:19.116846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c14fca5cfe'
down_revision = '9116f70715e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('appointment_time',
               existing_type=sa.TIME(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('appointment_time',
               existing_type=sa.String(),
               type_=sa.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
