"""added therapists to table

Revision ID: 53d3c63cbcf3
Revises: c7ac1f3123f0
Create Date: 2023-06-15 12:07:24.777548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d3c63cbcf3'
down_revision = 'c7ac1f3123f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('therapists',
    sa.Column('therapist_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_therapists_user_id_users')),
    sa.PrimaryKeyConstraint('therapist_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('therapists')
    # ### end Alembic commands ###
